version: '3.4'

services:
  moviereview-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      # Update your Web.config connection string to match this
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=MovieReview;User Id=sa;Password=Your_password123;"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-windowsservercore-1809
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    volumes:
      - ./db-init:/db-init
    command: >
      powershell -Command "
        Start-Process -NoNewWindow -FilePath 'sqlservr.exe';
        Start-Sleep -Seconds 20;
        sqlcmd -S localhost -U sa -P Your_password123 -d master -i C:\db-init\init.sql
      "

volumes:
  sqlserverdata: